- app/controllers/PanDomainAuthActions.scala
- build.sbt
provides Janus support and instance profile authentication
Replaces https://github.com/guardian/login.gutools/pull/5 too.
> use credentials provider chain for aws auth

- cloudformation/login-tool.json
This makes it highly available with 3 instances (one in each AZ) at a t2.micro size. This is the quantity and size that we have made reservations.
Also removes cfn-init metadata (no longer required) and parameterises the AMI ready for automatic updates on deploy.
Note: I've applied this to CODE and PROD already.
> Make highly available and unify on t2.micro

- README.md
- app/Global.scala
- app/actions/EmergencySwitchIsOnAction.scala
- app/config/LoginPublicSettings.scala
- app/controllers/Emergency.scala
- app/views/emergency/reissueDisabled.scala.html
- app/views/emergency/reissueFailure.scala.html
- app/views/emergency/reissueSuccess.scala.html
- build.sbt
- conf/application.code.conf
- conf/application.conf
- conf/application.local.conf
- conf/logback.xml
- conf/routes
If Google auth is down we want to be able to extend the cookie lifetime for users already signed in.
This feature is behind a configuration switch. To turn this on this will require a config change and redeploy. A future PR will change this to work with polling from S3.
If the switch is ON the following steps are taken 
* The `assymCookieName` cookie is read from request
*  An authenticated user is parsed from the cookie data and verified that it is a valid user
*  A new cookie is issued with to the verified user with an extended cookie time which is sent to the user's browser.
* The user will be sent an error message and the cookie will not be extended if the switch is off, the user is not signed in, the cookie data could not be parsed or the user could not be verified. 
To do:
* ~~This …
> Extends cookie if already signed in and emergency switch is on

- conf/logback.xml
`com.google.api.client.http.HttpTransport` is noisy at INFO level so moving to WARN level.
cc/ @adamnfish
> Change log level of com.google.api.client.http.HttpTransport 

- app/controllers/Login.scala
- conf/routes
It's extremely useful for serverless single page applications who want to know if the user is logged in and what's her email.
There's already an endpoint `/showUser` that is not exactly doing what it says, it simply returns `You are logged in` but has some iframe logic in it, so it didn't feel right to change it.
`/whoami` returns the JSON representation of the user or 401 if not logged in, which is what an API should do
> Add a who-am-I endpoint

- app/controllers/Login.scala
- app/model/Cors.scala
A bit convoluted (scala experts might be able to do better).
/whoami is a APIAuthAction so it requires credentials, however you can't use '*' when credentials is true.
Your only option is to read the Origin request header, validate and forward it back
The checks make sure that you can only use CORS from a gutools, which I guess is a good thing (your cookie shouldn't be valid on another domain anyway)
> Allow CORS for whoami

- deploy.json
Remove updating cloudformation from deploy to allow for checking cloudformation updates in more detail and to bring the login tool more in line with other apps. @jennysivapalan
> don't include cloudformation in deploy

- README.md
- script/debug
- script/start
Remove redundant instructions for brevity and include `script` directory.
> trim readme

- app/config/LoginConfig.scala
- app/controllers/Application.scala
- app/utils/Mailer.scala
- conf/routes
`digitalcms.bugs@guardian.co.uk` isn't DKIM verified and so messages being sent from it are not getting through. Use the updated team email to send emails from instead. This is the same email used within Preview too.
Also update email message to be more descriptive.
Example email:
> change from email address to editorial.tools.dev as its verified in SES

- app/AppComponents.scala
- app/controllers/LoginComponents.scala
- build.sbt
- conf/routes
- project/plugins.sbt
- riff-raff.yaml
We've not been deploying login.gutools for 14 months 😢 but this fixes it and bumps play-secret-rotation as well.
See CFN changes at https://github.com/guardian/editorial-tools-platform/pull/294
> Fix deployment issues with login.gutools

- app/AppComponents.scala
- app/AppLoader.scala
- app/config/AWS.scala
- app/config/LoginConfig.scala
- app/config/LoginPublicSettings.scala
- app/config/Switches.scala
- app/controllers/Application.scala
- app/controllers/Emergency.scala
- app/controllers/Login.scala
- app/controllers/LoginComponents.scala
- app/controllers/SwitchesController.scala
- app/utils/ElkLogging.scala
- app/utils/Loggable.scala
- app/utils/Mailer.scala
- build.sbt
- project/build.properties
- project/plugins.sbt
This PR adds central ELK logging to this project. In addition I did a little hygiene as I went along including:
- eliminating the global AWS object
- switching from play Logger to making `log` available from a trait
- adding `sbt-buildinfo` so we can track the code release from the logs
- bumping AWS SDK
> Log to central ELK plus hygiene

- README.md
- app/config/AWS.scala
- app/controllers/LoginComponents.scala
The pan-domain-auth-settings bucket has a policy which allows each of the Tools accounts to GetObject. This means we can use Composer credentials to access the required files to validate a cookie. That is, we can simplify the requirements of this app to a single set of Janus credentials, rather than two.
This also relates to https://github.com/guardian/janus/pull/2407 and https://github.com/guardian/janus/pull/2401 which create a new Janus role with access to the specific resources needed to run this app.
- Checkout branch
- Get Composer Janus credentials
- Run app
- Visit `https://login.local.dev-gutools.co.uk/logout` route to force a logout (or delete the cookie)
- Visit `https://login.local.dev-gutools.co.uk/whoami` and witness a 401 to confirm you do not have a valid cookie
- Visit …
> Use Composer profile to reach the pan-domain-auth-settings bucket.

- README.md
- script/get-emergency-login-link
The [Google outage of 14/12/20](https://www.theguardian.com/technology/2020/dec/14/google-suffers-worldwide-outage-with-gmail-youtube-and-other-services-down) also took down Gmail. This meant that users could extend their existing panda sessions but couldn't request new ones.
Providing the [emergency login switch is on](https://github.com/guardian/login.gutools#emergency-access-when-google-auth-is-down), to request a new session the user visits login.gutools.co.uk/emergency/request-cookie, types in their email address and we email them a token-based link. Once they click that we generate a new cookie for them. This naturally requires Gmail to be up and available to the user.
This PR adds a script that can be used by anyone with developer-level Composer Janus access to fish for the login …
> Script to fish for emergency login links if Gmail is down

- README.md
Adds the comms template Central Production send during login incidents
> Add Central Production comms to docs

- README.md
Adds a line in the instructions in the 'Emergency access when Google auth is down' section of the README to indicate which table to edit in DynamoDB.
> Update instructions to include DynamoDB table

- app/AppComponents.scala
- app/config/AWS.scala
- app/controllers/Application.scala
- app/controllers/Emergency.scala
- app/controllers/Login.scala
- app/controllers/LoginComponents.scala
- app/controllers/SwitchesController.scala
- app/services/EmergencyUserDBservice.scala
- app/services/TokenDBService.scala
- build.sbt
Updates Scanamo to latest, 1.0.0-M17.
This is a more involved change than we might expect for two reasons:
- Scanamo latest requires AWS SDK V2, which means configuring and scaffolding for a new dependency (coexisting with V1)
- The changes to Scanamo's table configuration were significant enough that I felt it was a good time to abstract the DB ops away from our controllers into their own services.
It paves the way for updating Scala to 2.13.
This change should be a no-op. Test the following locally, or in CODE (I've tested in CODE where ticked):
> Update Scanamo to 1.0.0-M17

- .github/workflows/ci.yml
- app/controllers/Application.scala
- app/management/BuildInfo.scala
- app/utils/ElkLogging.scala
- build.sbt
- project/plugins.sbt
Adopts GitHub Actions for CI, replacing TeamCity. This involves removing the deprecated SBT plugin [sbt-riffraff-artifact](https://github.com/guardian/sbt-riffraff-artifact) in favour of [https://github.com/guardian/actions-riff-raff](https://github.com/guardian/actions-riff-raff).
There are four tests we can do.
1. [Deploy this branch. It should succeed](https://riffraff.gutools.co.uk/deployment/view/ec57aa40-0fe7-423e-9f58-7faf575535d7).
2. With this branch on CODE, interact with another service that uses login.gutools CODE, for example [S3 Uploader](https://s3-uploader.code.dev-gutools.co.uk/). You should successfully login.
3. On [`main`](https://github.com/guardian/login.gutools/blob/54c7067f71b98c689f174d704c018e0135bf6394/app/controllers/Application.scala#L16-L18), the …
> ci: Adopt GitHub Actions for CI

- README.md
`.bcrypt` is depreacted. This is a particular problem for us since we treat warnings as errors, so the documentation on password hashing no longer works.
Here is the error:
```
warning: method bcrypt in class BCryptStrOps is deprecated (since 4.3.0): Use boundedBcrypt instead.
More information at https://github.com/t3hnar/scala-bcrypt/issues/23
```
Also updates the README to acknowledge that if Google auth is down, Janus may be unavailable.
> Update docs to use non-deprecated method

- app/AppComponents.scala
- app/config/LoginConfig.scala
- app/controllers/Application.scala
- app/controllers/DesktopLogin.scala
- app/controllers/Emergency.scala
- app/controllers/Login.scala
- app/controllers/LoginComponents.scala
- app/controllers/SwitchesController.scala
- conf/routes
adds a new controller and group of endpoints for facilitating auth for non-browser apps
currently various flexible-content apis made available to machines and non-browser user agents (namely incopy & indesign plugins & scripts) are provided access purely through network rules. this saved having to manage stronger authentication systems but meant that clients had to be logged into the privileged networks to gain access, which is a problem when that network sometimes goes down, or more generally we move to be a less office-centric business. As such, we want to make those APIs available on the wider internet, which means we need to address the authentication problem.
Machine clients are no problem; we already have a scheme for sending requests with HMAC: …
> send token to desktop apps to facilitate non-browser logins

- app/controllers/DesktopLogin.scala
We've changed our mind and no longer want these to be handled by the same app as the other gnm:// links... 
Instead we've decided to pass it to a new app, which means a new scheme (we've picked gu-panda://) and an opportunity to use a more sensible parameter scheme (ie. using query params instead of path segments)
> update to newly agreed gu-panda:// scheme

- app/controllers/DesktopLogin.scala
The desktop apps will use this endpoint to check if they're still logged in, so their grace period should match the flex grace period (to avoid unnecessarily frequent reauths)
> Make desktoplogin check have 9hr grace period to match flex-integration

- app/controllers/DesktopLogin.scala
- app/views/clientSideRedirectToLogin.scala.html
- conf/routes
…to hopefully work around an issue when opening Chrome for the first time with an url that ultimately redirects back to an url with 'custom scheme'
> add a new `/desktop/loginRedirect` endpoint which performs a client-side redirect to `/desktop/login`

- app/controllers/DesktopLogin.scala
- build.sbt
This PR upgrades our [pan-domain-authentication](https://github.com/guardian/pan-domain-authentication) (panda) libraries to v4, which is a vital step towards our plan to improve key rotation.
[Check](https://riffraff.gutools.co.uk/deployment/history?projectName=editorial-tools%3Alogin&stage=CODE&pageSize=20&page=1) if this branch is deployed to CODE. If not, deploy to [CODE](https://login.code.dev-gutools.co.uk/)[^1].
We want to test that the Panda library can: 
(1) verify valid Panda cookies
(2) issue Panda cookies through OAuth
(3) issue cookies that work 'pan domain', i.e. across tools on the same domain (in this case, dev-gutools.co.uk)
(4) **but wait this time there's more!** login.gutools logs other tools in with panda (which may not be able to issue panda cookies themselves) - we …
> Upgrade to panda v4

- app/AppComponents.scala
- app/controllers/DesktopLogin.scala
- app/controllers/Emergency.scala
- build.sbt
This upgrades Panda from v5 to v7, allowing us to [perform key rotation](https://github.com/guardian/pan-domain-authentication/pull/150).
As login.gutools.co.uk is pretty special user of Panda, the upgrade is slightly more involved than other upgrades (eg https://github.com/guardian/atom-workshop/pull/361):
* Panda v6:
* https://github.com/guardian/pan-domain-authentication/pull/152 means the `CookieUtils.generateCookieData()` method now communicates errors with `CookieResult` values containing `CookieIntegrityFailure`, rather than exceptions.
* https://github.com/guardian/pan-domain-authentication/pull/151 introduced the new `S3BucketLoader` abstraction, which simplifies constructing a `PanDomainAuthSettingsRefresher` and means that Panda is no longer _tied_ to AWS SDK v1 - an …
> Upgrade to Panda v7 - support key rotation

- CODEOWNERS
The [Workflow and Collaboration team](https://github.com/orgs/guardian/teams/workflow-and-collaboration) are [taking ownership of panda](https://github.com/guardian/pan-domain-authentication/pull/189), and we feel it makes sense for us to also take ownership of this repository as it is so closely related. This PR therefore sets the code owner for this repository to be us.
- confirm that github flags the code owners file as valid in the UI
- after merge, test that opening a new PR requests a code owner review from Workflow and Collaboration
> Set code owner to workflow-and-collaboration

- build.sbt
This pull request bumps the AWS SDK v2 to the latest version (2.31.19), which updates the transitive dependency on netty-codec-http2 to version 4.1.118.  This netty version should have fixed the [vulnerability](https://github.com/advisories/GHSA-xpw8-rcwv-8f8p) found in the older versions (prior to 4.1.100).
In Incognito window, I opened "https://login.code.dev-gutools.co.uk/login?returnUrl=https://composer.code.dev-gutools.co.uk/".  It forwarded the browser to Google sign-in.  After sign-in, it redirected me to the Composer CODE.
I also opened "https://login.code.dev-gutools.co.uk/whoami" and it could return my account info.
> Bump AWS SDK v2 to fix vulnerability on netty-codec-http2

- .gitignore
- app/AppComponents.scala
- app/config/AWS.scala
- app/controllers/DesktopLogin.scala
- app/controllers/Emergency.scala
- app/controllers/LoginComponents.scala
- app/utils/Mailer.scala
- build.sbt
Upgrade AWS SDK from v1 to v2
AWS SDK for Java v1 will be EOL on 31st December 2025, and has been in Maintenance mode since [31st July 2024](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/). So we have to  upgrade to AWS SDK v2.
[Issue](https://github.com/guardian/login.gutools/issues/103)
1.Deploy the branch to CODE 
2.Open up [login.gutools CODE](https://login.code.dev-gutools.co.uk/)
Check if we are receiving a 200 response
3. Open any tool that requires the user to login eg:S3Uploader in a new Incognito window
4. Check if it asking to login 
5. On clicking the 'here' link, it should take the user to login page 
6. Enter the details to sign in and check if you are taken to the tool 
[Upgrading to AWS SDK …
> Upgrade AWS SDK to V2
